name: dbus_client
version: 0.0.0-dev.4
description: Native DBus client library.
homepage: https://github.com/CanonicalLtd/dbus_client.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  unix_domain_socket: ^0.0.0-dev
